version: '3'

services:
  database:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'productAPI'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./cleanData:/tmp

  service_server:
    build: .
    depends_on:
      'database':
        condition: service_healthy
    ports:
      - '5000:5000'
