version: '3'

services:
  database:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'productAPI'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  service_server:
    image: danaewalsh/hr_sdc:service_server1.0
    restart: on-failure
    depends_on:
      - database
        condition: service_healthy
    ports:
      - '5000:5000'
